### ISSUE TITLE
Exploration not starting in ROS Noetic, Ubuntu 20.04

### ISSUE THREAD

**Issue by Cypre55** [larics/nbvp_exploration#3]
Hello,

I have tried to clone the nbvp_exploration planner in my machine.
ROS Distro: Noetic
OS: Ubuntu 20.04

### Modifications

I have followed the instructions from the wiki. I had to do a few minor changes, namely:

* Adding CATKIN_IGNORE files in `nbvp_exploration/catkin_simple` and `nbvp_exploration/glog_catkin`
* Add paranthesis to print statement on line 58 of `nbvp_exploration/interface_nbvp_rotors/src/execute_trajectory_state_machine.py`
* Changing `--std=c++11` to `--std=c++14` in CMakeLists.txt files of `nbvp_exploration/interface_nbvp_rotors`, `nbvp_exploration/nbvplanner`, `nbvp_exploration/volumetric_mapping/octomap_world` and `nbvp_exploration/volumetric_mapping/volumetric_map_base`
* Modify the paths mentioned in lines 2, 3, 4 ,5, 6, 68 of `nbvp_exploration/interface_nbvp_rotors/resource/kopterworx_config.yaml`
* Modified RViz file path in `nbvp_exploration/startup/kopterworx_one_flying/session.yml`

Additionally, I had made a few changes in the dependent packages.
* Change `OMPL` to `ompl` on line 25 of CMakeLists.txt in `larics_motion_planning` 
* Adding a `return true` at the end of the following functions as there was a "Double Free" issue 
  * `configurefromFile` in `larics_motion_planning/src/RrtPathPlanner.cpp` 
  * `configurefromFile` in `larics_motion_planning/src/ToppraTrajectory.cpp`
* Revert `uav_ros_tracker` to commit `17193af`
  * Because I faced the following error when launching `topp_tracker.launch` in the `trajectory` window of TMUX
  
```bash
Traceback (most recent call last):
File
" /home/satwik/nbvp_ws/src/uav_ros_simulation/ros_packages/uav_ros_stack/ros_packa ges/uav_ros_tracker/scripts/topp-tracker.py", line 456, in <module>
tracker = ToppTracker ()
File
" /home/satwik/nbvp_ws/src/uav_ros_simulation/ros_packages/uav_ros_stack/ros_packa ges/uav_ros_tracker/scripts/topp_tracker.py", line 46, in _
init
self.tracker_params.from_odom = rospy.get_param("~topp_tracker/from_odom")
File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 467, in get_param
return _param_server [param_name] #MasterProxy does all the magic for us File "/opt/ros/noetic/lib/python3/dist-packages/rospy/msproxy.py", line 123, in __getitem_
raise KeyError (key)
KeyError: '-topp_tracker/from_odom
  ``` 

### Running

With all the above changes, all packages build with errors. On starting the simulation, all the tmux panes are error-free.
When the drone takes off, it drifts from the starting position. (**EDIT** RViz does not recognize this drift)

Now, when I run `waitForRos; waitForOdometry; roslaunch interface_nbvp_rotors kopterworx_exploration.launch`

Console:
```
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame red/base_link at time 6201.435000 according to authority unknown_publisher
         at line 278 in /tmp/binarydeb/ros-noetic-tf2-0.7.6/src/buffer_core.cpp
```
which is expected when using ROS Noetic

```
Error getting TF transform from sensor data:
 Could not find a connection between 'mavros/world' and 'velodyne' because they are not part
 of the same tree.Tf has two or more unconnected trees.
```

Between all these messages, I found the following lines
```
[ INFO] [1678256752.524437151, 5796.437000000]: Planning iteration 9                                                                                                                          
[ INFO] [1678256752.524476765, 5796.437000000]: Iteration started at  5796.43700s                                                                                                             
[ WARN] [1678256752.526166313, 5796.438000000]: History size: 0
```

I noticed 2 different types of outcomes.
Outcome 1: The drone stays still.
Outcome 2: The drone crashes into a wall

RViz shows that the planning is taking place and is exploring the map, but not in Gazebo

I am attaching the list of topics and the TF Tree [frames.pdf](https://github.com/larics/nbvp_exploration/files/10918667/frames.pdf).

```
/clicked_point
/clock
/diagnostics
/gazebo/link_states
/gazebo/model_states
/gazebo/parameter_descriptions
/gazebo/parameter_updates
/gazebo/performance_metrics
/gazebo/set_link_state
/gazebo/set_model_state
/gazebo/wind_speed
/initialpose
/motor_speed
/move_base_simple/goal
/red/cam0/camera_info
/red/cam1/camera_info
/red/camera/color/camera_info
/red/camera/color/image_raw
/red/camera/color/image_raw/compressed
/red/camera/color/image_raw/compressed/parameter_descriptions
/red/camera/color/image_raw/compressed/parameter_updates
/red/camera/color/image_raw/compressedDepth
/red/camera/color/image_raw/compressedDepth/parameter_descriptions
/red/camera/color/image_raw/compressedDepth/parameter_updates
/red/camera/color/image_raw/theora
/red/camera/color/image_raw/theora/parameter_descriptions
/red/camera/color/image_raw/theora/parameter_updates
/red/camera/depth/camera_info
/red/camera/depth/image_raw
/red/camera/depth_registered/points
/red/camera_ir/parameter_descriptions
/red/camera_ir/parameter_updates
/red/carrot/pose
/red/carrot/status
/red/carrot/trajectory
/red/carrot/velocity
/red/carrot/yaw
/red/cartesian_path
/red/cascade_config/parameter_descriptions
/red/cascade_config/parameter_updates
/red/comp_times
/red/disparity
/red/executing_trajectory
/red/exploration/current_state
/red/gazebo/command/motor_speed
/red/imu
/red/input_octomap
/red/inspectionPath
/red/inspectionPath_array
/red/joint_states
/red/joint_trajectory
/red/joy
/red/mavlink/from
/red/mavlink/gcs_ip
/red/mavlink/to
/red/mavros/adsb/send
/red/mavros/adsb/vehicle
/red/mavros/battery
/red/mavros/cam_imu_sync/cam_imu_stamp
/red/mavros/camera/image_captured
/red/mavros/cellular_status/status
/red/mavros/companion_process/status
/red/mavros/distance_sensor/rangefinder_pub
/red/mavros/distance_sensor/rangefinder_sub
/red/mavros/esc_info
/red/mavros/esc_status
/red/mavros/esc_telemetry
/red/mavros/estimator_status
/red/mavros/extended_state
/red/mavros/fake_gps/mocap/tf
/red/mavros/geofence/waypoints
/red/mavros/global_position/compass_hdg
/red/mavros/global_position/global
/red/mavros/global_position/gp_lp_offset
/red/mavros/global_position/gp_origin
/red/mavros/global_position/home
/red/mavros/global_position/local
/red/mavros/global_position/raw/fix
/red/mavros/global_position/raw/gps_vel
/red/mavros/global_position/raw/satellites
/red/mavros/global_position/rel_alt
/red/mavros/global_position/set_gp_origin
/red/mavros/gps_input/gps_input
/red/mavros/gps_rtk/rtk_baseline
/red/mavros/gps_rtk/send_rtcm
/red/mavros/gpsstatus/gps1/raw
/red/mavros/gpsstatus/gps1/rtk
/red/mavros/gpsstatus/gps2/raw
/red/mavros/gpsstatus/gps2/rtk
/red/mavros/home_position/home
/red/mavros/home_position/set
/red/mavros/imu/data
/red/mavros/imu/data_raw
/red/mavros/imu/diff_pressure
/red/mavros/imu/mag
/red/mavros/imu/static_pressure
/red/mavros/imu/temperature_baro
/red/mavros/imu/temperature_imu
/red/mavros/landing_target/lt_marker
/red/mavros/landing_target/pose
/red/mavros/landing_target/pose_in
/red/mavros/local_position/accel
/red/mavros/local_position/odom
/red/mavros/local_position/pose
/red/mavros/local_position/pose_cov
/red/mavros/local_position/velocity_body
/red/mavros/local_position/velocity_body_cov
/red/mavros/local_position/velocity_local
/red/mavros/log_transfer/raw/log_data
/red/mavros/log_transfer/raw/log_entry
/red/mavros/mag_calibration/report
/red/mavros/mag_calibration/status
/red/mavros/manual_control/control
/red/mavros/manual_control/send
/red/mavros/mission/reached
/red/mavros/mission/waypoints
/red/mavros/mocap/pose
/red/mavros/mount_control/command
/red/mavros/mount_control/orientation
/red/mavros/mount_control/status
/red/mavros/nav_controller_output
/red/mavros/obstacle/send
/red/mavros/odometry/in
/red/mavros/odometry/out
/red/mavros/onboard_computer/status
/red/mavros/param/param_value
/red/mavros/play_tune
/red/mavros/radio_status
/red/mavros/rallypoint/waypoints
/red/mavros/rangefinder/rangefinder
/red/mavros/rc/in
/red/mavros/rc/out
/red/mavros/rc/override
/red/mavros/setpoint_accel/accel
/red/mavros/setpoint_attitude/attitude
/red/mavros/setpoint_attitude/thrust
/red/mavros/setpoint_position/global
/red/mavros/setpoint_position/global_to_local
/red/mavros/setpoint_position/local
/red/mavros/setpoint_raw/attitude
/red/mavros/setpoint_raw/global
/red/mavros/setpoint_raw/local
/red/mavros/setpoint_raw/target_attitude
/red/mavros/setpoint_raw/target_global
/red/mavros/setpoint_raw/target_local
/red/mavros/setpoint_trajectory/desired
/red/mavros/setpoint_trajectory/local
/red/mavros/setpoint_velocity/cmd_vel
/red/mavros/setpoint_velocity/cmd_vel_unstamped
/red/mavros/state
/red/mavros/statustext/recv
/red/mavros/statustext/send
/red/mavros/terrain/report
/red/mavros/time_reference
/red/mavros/timesync_status
/red/mavros/trajectory/desired
/red/mavros/trajectory/generated
/red/mavros/trajectory/path
/red/mavros/tunnel/in
/red/mavros/tunnel/out
/red/mavros/vfr_hud
/red/mavros/vision_pose/pose
/red/mavros/vision_pose/pose_cov
/red/mavros/wind_estimation
/red/motor_speed
/red/multi_dof_trajectory
/red/nbvPlanner/nearest_obstacle
/red/nbvPlanner/octomap_binary
/red/nbvPlanner/octomap_free
/red/nbvPlanner/octomap_full
/red/nbvPlanner/octomap_occupied
/red/nbvPlanner/octomap_pcl
/red/nbvp/goals
/red/nbvp/point_reached
/red/nbvp/target
/red/octomap_binary
/red/octomap_volume
/red/odometry
/red/parabolic_airdrop/info_vector
/red/peer_pose_1
/red/peer_pose_2
/red/peer_pose_3
/red/pointcloud
/red/pointcloud_throttled_down
/red/pointcloud_throttled_up
/red/pose
/red/pose_with_covariance
/red/position
/red/position_hold/trajectory
/red/smece
/red/toppra_raw_trajectory
/red/toppra_raw_waypoints
/red/tracker/input_pose
/red/tracker/input_trajectory
/red/tracker/path
/red/tracker/remaining_trajectory
/red/tracker/status
/red/transform
/red/uav/euler_setpoint
/red/uav/velocity
/red/uav/yaw
/red/velocity_relative
/red/velodyne_points
/red/visualization/path
/red/visualization/state_points
/red/visualization/trajectory
/red/visualization/waypoints
/rosout
/rosout_agg
/tf
/tf_static

```

I think I have not missed out any details for reproducing my issue. Please let me know if any of the above changes are problematic or any further modifications I need to make.

#### Edit

Workspace Name: nbvp_ws

I also tried uncommenting `waitForRos; waitForOdometry; roslaunch interface_nbvp_rotors kopterworx_exploration.launch` in `session.yml` file to start exploration right after Odometry is found.
I ran this 4 times.

One time the exploration began, but crashed into a wall
Three times the drone moved from the starting point and stays still.

**Comment by fpetric** [comment]
@AnaBatinovic can you take a look on this?

**Comment by eliabntt** [comment]
Hi, I noticed the same behaviour. Although I used the `uav_ws` generated by the simulator installation.

**Comment by AnaBatinovic** [comment]
Hi @Cypre55 @eliabntt, thanks for using the repo. Originally the code was tested on ROS Melodic. I'm currently trying to reproduce this issue on ROS Noetic and will keep you posted.

**Comment by kailash197** [comment]
hi @AnaBatinovic do we have any further update on this?
@Cypre55 were you able to run it ?
